version: '3'

services:
  parent_control_service:
    image: dzhuang/parent_control:latest
    ports:
      - 8030:8030
    volumes:
      - ./parent_control/database:/opt/parent_control/database
      # - D:/dev/parent_control/parent_control/local_settings/:/opt/parent_control/local_settings/
    environment:
      - PARENT_CONTROL_SERVER_SECRET_KEY=pclpourladjfoupuigjladfj2qyqewrozcoilqepouipoigpqeroilijapoiqer
      # - PARENT_CONTROL_SERVER_LANGUAGE_CODE=zh-hans
      # - PARENT_CONTROL_SERVER_TZ=Asia/Shanghai
      - PARENT_CONTROL_SERVER_DEBUG=on
      - PARENT_CONTROL_SERVER_REDIS_LOCATION=redis://redis_service:6379

      - DJANGO_SUPERUSER_USERNAME=pc_test
      - DJANGO_SUPERUSER_PASSWORD=pc_test
      - DJANGO_SUPERUSER_EMAIL=blabal@example.com
    depends_on:
      - redis_service
    restart: always

  redis_service:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  celery:
    image: dzhuang/parent_control:latest
    command: celery -A parent_control worker -l INFO
    environment:
      - PARENT_CONTROL_SERVER_REDIS_LOCATION=redis://redis_service:6379
    volumes:
      - ./parent_control/database:/opt/parent_control/database
    depends_on:
      - parent_control_service
      - redis_service

  celery-beat:
    image: dzhuang/parent_control:latest
    command: celery -A parent_control beat -l INFO
    environment:
      - PARENT_CONTROL_SERVER_REDIS_LOCATION=redis://redis_service:6379
    volumes:
      - ./parent_control/database:/opt/parent_control/database
    depends_on:
      - parent_control_service
      - redis_service

volumes:
  redis_data:
