from copy import deepcopy

DEVICE0_MAC = "00-11-22-33-44-55"
DEVICE1_MAC = "22-33-44-55-66-77"
BLOCKED_DEVICE1_MAC = "BB-BB-BB-BB-BB-B1"
BLOCKED_DEVICE2_MAC = "BB-BB-BB-BB-BB-B2"
LIMIT_DEVICE1_MAC = "33-33-33-33-33-33"
LIMIT_DEVICE2_MAC = "44-44-44-44-44-44"
ADDED_DEVICE_MAC = "55-55-55-55-55-55"


restructured_info_dicts1 = {
    'forbid_domain': {
        'forbid_domain_1': {
            '.anonymous': False,
            '.index': 4,
            '.name': 'forbid_domain_1',
            '.type': 'forbid_domain',
            'domain': 'www.example1.com'},
        'forbid_domain_2': {
            '.anonymous': False,
            '.index': 23,
            '.name': 'forbid_domain_2',
            '.type': 'forbid_domain',
            'domain': 'www.foo.com'},
        'forbid_domain_3': {
            '.anonymous': False,
            '.index': 29,
            '.name': 'forbid_domain_3',
            '.type': 'forbid_domain',
            'domain': 'www.foobar.com'},
        'forbid_domain_4': {
            '.anonymous': False,
            '.index': 30,
            '.name': 'forbid_domain_4',
            '.type': 'forbid_domain',
            'domain': 'www.bar.com'},
        'forbid_domain_5': {
            '.anonymous': False,
            '.index': 31,
            '.name': 'forbid_domain_5',
            '.type': 'forbid_domain',
            'domain': 'www.foo_bar.com'},
    },
    'host_info': {
        DEVICE0_MAC: {
            'blocked': '0',
            'down_limit': '0',
            'down_speed': '0',
            'forbid_domain': '',
            'hostname': 'CONTROL_HOST',
            'ip': '192.168.0.119',
            'is_cur_host': '1',
            'limit_time': '',
            'mac': DEVICE0_MAC,
            'plan_rule': [],
            'type': '0',
            'up_limit': '0',
            'up_speed': '0'},
        DEVICE1_MAC: {
            'acs_time': '2022-02-10 12:35:20',
            'ap_radio': 2,
            'blocked': '0',
            'down_limit': '0',
            'down_speed': '0',
            'encode': 1,
            'forbid_domain': '',
            'freq_unit': 1,
            'hostname': 'DEVICE1',
            'id': '44',
            'ip': '192.168.0.116',
            'is_cur_host': '0',
            'limit_time': '',
            'mac': DEVICE1_MAC,
            'plan_rule': [],
            'rssi': '-63',
            'ssid': 'SSID',
            'type': '1',
            'up_limit': '0',
            'up_speed': '0',
            'vlan': '0',
            'wifi_mode': 0,
            'wserv_id': 0},
        BLOCKED_DEVICE1_MAC: {
            'blocked': '1',
            'down_limit': '0',
            'down_speed': '0',
            'forbid_domain': '',
            'hostname': 'BLOCKED_DEVICE1',
            'ip': '0.0.0.0',
            'is_cur_host': '0',
            'limit_time': 'limit_time_1',
            'mac': BLOCKED_DEVICE1_MAC,
            'plan_rule': [],
            'type': '0',
            'up_limit': '0',
            'up_speed': '0'},
        BLOCKED_DEVICE2_MAC: {
            'blocked': '1',
            'down_limit': '0',
            'down_speed': '0',
            'forbid_domain': '',
            'hostname': 'BLOCKED_DEVICE2',
            'ip': '0.0.0.0',
            'is_cur_host': '0',
            'limit_time': '',
            'mac': BLOCKED_DEVICE2_MAC,
            'plan_rule': [],
            'type': '0',
            'up_limit': '0',
            'up_speed': '0'},
        LIMIT_DEVICE1_MAC: {
            'acs_time': '2022-02-10 02:46:37',
            'ap_radio': 2,
            'blocked': '0',
            'down_limit': '0',
            'down_speed': '0',
            'encode': 1,
            'forbid_domain': 'forbid_domain_3,forbid_domain_4',
            'freq_unit': 1,
            'hostname': 'LIMITED_HOST1',
            'id': '3',
            'ip': '192.168.0.115',
            'is_cur_host': '0',
            'limit_time': '',
            'mac': LIMIT_DEVICE1_MAC,
            'plan_rule': [],
            'rssi': '-42',
            'ssid': 'SSID',
            'type': '1',
            'up_limit': '0',
            'up_speed': '10',
            'vlan': '0',
            'wifi_mode': 0,
            'wserv_id': 0},
        LIMIT_DEVICE2_MAC: {
            'acs_time': '2022-02-10 02:46:40',
            'ap_radio': 2,
            'blocked': '0',
            'down_limit': '0',
            'down_speed': '0',
            'encode': 1,
            'forbid_domain': 'forbid_domain_1',
            'freq_unit': 1,
            'hostname': 'LIMITED_HOST2',
            'id': '5',
            'ip': '192.168.0.111',
            'is_cur_host': '0',
            'limit_time': 'limit_time_1,limit_time_3',
            'mac': LIMIT_DEVICE2_MAC,
            'plan_rule': [],
            'rssi': '-66',
            'ssid': 'SSID',
            'type': '1',
            'up_limit': '5',
            'up_speed': '0',
            'vlan': '0',
            'wifi_mode': 0,
            'wserv_id': 0}
    },
    'limit_time': {
        'limit_time_1': {
            '.anonymous': False,
            '.index': 21,
            '.name': 'limit_time_1',
            '.type': 'limit_time',
            'end_time': '18:10',
            'fri': '0',
            'mon': '0',
            'name': 'PRE_SUPPER',
            'sat': '1',
            'start_time': '17:30',
            'sun': '1',
            'thu': '0',
            'tue': '0',
            'wed': '0'},
        'limit_time_3': {
            '.anonymous': False,
            '.index': 22,
            '.name': 'limit_time_3',
            '.type': 'limit_time',
            'end_time': '22:00',
            'fri': '1',
            'mon': '1',
            'name': 'EVE',
            'sat': '1',
            'start_time': '21:10',
            'sun': '1',
            'thu': '1',
            'tue': '1',
            'wed': '1'},
        'limit_time_4': {
            '.anonymous': False,
            '.index': 25,
            '.name': 'limit_time_4',
            '.type': 'limit_time',
            'end_time': '23:59',
            'fri': '1',
            'mon': '1',
            'name': 'ALL TIME',
            'sat': '1',
            'start_time': '00:00',
            'sun': '1',
            'thu': '1',
            'tue': '1',
            'wed': '1'},
        'limit_time_5': {
            '.anonymous': False,
            '.index': 26,
            '.name': 'limit_time_5',
            '.type': 'limit_time',
            'end_time': '08:00',
            'fri': '1',
            'mon': '1',
            'name': 'MORNING',
            'sat': '1',
            'start_time': '11:00',
            'sun': '1',
            'thu': '1',
            'tue': '1',
            'wed': '1'}
    }}

restructured_info_dicts2 = deepcopy(restructured_info_dicts1)
_hosts = restructured_info_dicts2["host_info"]
_hosts[DEVICE0_MAC]["ip"] = "192.168.0.129"
_hosts[DEVICE1_MAC]["hostname"] = "DEVICE1_RENAMED"
_hosts.pop(LIMIT_DEVICE2_MAC)
_hosts[ADDED_DEVICE_MAC] = {
    'acs_time': '2022-02-10 02:46:37',
    'ap_radio': 2,
    'blocked': '0',
    'down_limit': '0',
    'down_speed': '0',
    'encode': 1,
    'forbid_domain': 'forbid_domain_3,forbid_domain_2',
    'freq_unit': 1,
    'hostname': 'ANOTHER_HOST',
    'id': '3',
    'ip': '192.168.0.188',
    'is_cur_host': '0',
    'limit_time': 'limit_time_4',
    'mac': ADDED_DEVICE_MAC,
    'plan_rule': [],
    'rssi': '-41',
    'ssid': 'SSID',
    'type': '1',
    'up_limit': '0',
    'up_speed': '10',
    'vlan': '0',
    'wifi_mode': 0,
    'wserv_id': 0}

_limit_time = restructured_info_dicts2["limit_time"]
_limit_time.pop("limit_time_1")

_forbid_domain = restructured_info_dicts2["forbid_domain"]
_forbid_domain.pop("forbid_domain_1")

restructured_info_dicts2["host_info"] = _hosts
