# Generated by Django 3.2.12 on 2022-02-07 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import my_router.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Router name')),
                ('description', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(help_text='The URL of the router')),
                ('admin_password', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Router model')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('mac_address', my_router.fields.MACAddressField(db_index=True, max_length=17)),
                ('known', models.BooleanField(default=False, help_text='This devices is known.')),
                ('ignore', models.BooleanField(default=False, help_text='This device will be ignored when listing and bulk applying limit time or forbid domain constraints.')),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added datetime')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_router.router')),
            ],
            options={
                'unique_together': {('router', 'mac_address')},
            },
        ),
    ]
