# Generated by Django 3.2.12 on 2022-02-11 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_router', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mac',
            new_name='mac',
        ),
        migrations.AlterField(
            model_name='router',
            name='fetch_interval',
            field=models.PositiveIntegerField(default=10, help_text='The interval of the app to fetch the information on the router, in seconds', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Fetch interval'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('router', 'mac')},
        ),
    ]
